name: anything_gpt
description: AI assistant capable of answering any questions and generating images from text prompts

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

  # State management
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  equatable: ^2.0.3
  provider: ^6.0.5

  # Local database
  hive: ^2.1.0
  hive_flutter: ^1.1.0

  # Animation
  lottie: ^2.5.0
  avatar_glow: ^2.0.2
  animated_text_kit: ^4.2.2
  flutter_animate: ^4.1.1+1

  # Speech recognition
  speech_to_text: ^6.3.0

  # Networking
  dio: ^5.1.2

  # Firebase
  google_sign_in: ^6.1.4
  firebase_auth: ^4.7.1
  firebase_core: ^2.15.0
  firebase_remote_config: ^4.2.4
  firebase_analytics: ^10.4.4

  # Logging
  logger: ^1.1.0

  # Text
  auto_size_text: ^3.0.0
  google_fonts: ^4.0.4

  # Widgets
  flutter_svg: ^2.0.7
  dropdown_button2: ^2.1.4
  flutter_countdown_timer: ^4.1.0
  universal_html: ^2.2.3
  fluttertoast: ^8.0.9
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
